# Generated by Django 5.0 on 2024-02-03 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_event_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
