# Generated by Django 5.0 on 2024-02-06 17:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_event_end_time_event_location_event_start_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='date_created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
