# Generated by Django 5.0 on 2024-02-07 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_volunteer_date_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormResponse',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('content', models.CharField(max_length=5000)),
                ('satisfaction', models.IntegerField()),
            ],
        ),
    ]
