# Generated by Django 5.0 on 2024-02-07 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_formresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='formresponse',
            name='inference_reason',
            field=models.CharField(default='No reason', max_length=1000),
            preserve_default=False,
        ),
    ]
