# Generated by Django 5.0 on 2024-02-07 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_formresponse_inference_reason'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formresponse',
            old_name='inference_reason',
            new_name='reason',
        ),
    ]
