# Generated by Django 5.0 on 2024-02-07 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_inference_reason_formresponse_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='formresponse',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.event'),
            preserve_default=False,
        ),
    ]
