# Generated by Django 5.0 on 2024-02-07 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_formresponse_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='formresponse',
            name='submit_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
