# Generated by Django 5.0 on 2024-02-08 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_formresponse_submit_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='google_form_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
