# fly.toml app configuration file generated for hack4good-server on 2024-02-09T22:39:43+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'hack4good-server'
primary_region = 'sin'
console_command = '/code/manage.py shell'

[build]

[env]
  PORT = '8000'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512

[[statics]]
  guest_path = '/code/static'
  url_prefix = '/static/'
